# This workflow will build a .NET project
# Basic .NET workflow - helps with Continuos Integration and Conitnuos Development

name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'  # Adjust this based on your project version

      - name: Restore dependencies
        run: dotnet restore src/Magna.Dexsys.FileHandler/Magna.Dexsys.FileHandler.sln

      - name: Build project
        run: dotnet build src/Magna.Dexsys.FileHandler/Magna.Dexsys.FileHandler.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test src/Magna.Dexsys.FileHandler/Magna.Dexsys.FileHandlerTests/Magna.Dexsys.FileHandlerTests.csproj --no-build --verbosity normal

